'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { useLocale } from '@/i18n/LocaleProvider';
import { LOCALE_TAGS } from '@/i18n/types';
import { calculate, defaults, type ForecastState, type Scenario } from './forecast/model';
import { forecastMessages } from './forecast/messages';
import './forecast/forecast.css';

interface Props { income: number | null; expense: number | null; coverage: React.ReactNode; loading?: boolean; accountScope?: string | null }
const STORAGE = 'gastos.forecast.selected11.v1';
export default function ForecastDashboard({ income, expense, coverage, loading = false, accountScope = null }: Props) {
  const { locale } = useLocale(), m = forecastMessages[locale];
  const storageKey = accountScope ? `${STORAGE}:${encodeURIComponent(accountScope)}` : null;
  const [state, setState] = useState(defaults), [tab, setTab] = useState(0), [step, setStep] = useState(0), [name, setName] = useState(''), [status, setStatus] = useState('');
  const edited = useRef({ A: { income: false, essential: false }, B: { income: false, essential: false } });
  useEffect(() => {
    if (income === null && expense === null) return;
    setState(old => ({ ...old, A: { ...old.A, ...(!edited.current.A.income && income !== null ? { income } : {}), ...(!edited.current.A.essential && expense !== null ? { essential: expense } : {}) }, B: { ...old.B, ...(!edited.current.B.income && income !== null ? { income } : {}), ...(!edited.current.B.essential && expense !== null ? { essential: expense } : {}) } }));
  }, [income, expense]);
  const a = useMemo(() => calculate(state, 'A'), [state]), b = useMemo(() => calculate(state, 'B'), [state]);
  const money = (value: number | null | undefined) => value !== null && value !== undefined && Number.isFinite(value) ? new Intl.NumberFormat(LOCALE_TAGS[locale], { style: 'currency', currency: 'NZD', maximumFractionDigits: 0 }).format(value) : '—';
  const bucketName = (id: string) => state.buckets.find(bucket => bucket.id === id)?.name || (id === 'emergency' ? m.emergency : m.bucketName);
  const shared = (key: keyof ForecastState, value: number | string | boolean) => setState(old => ({ ...old, [key]: value }));
  const update = (key: 'A' | 'B', field: keyof Scenario, value: number | null) => {
    if (field === 'income' || field === 'essential') edited.current[key][field] = true;
    setState(old => ({ ...old, [key]: { ...old[key], [field]: value } }));
  };
  const input = (label: string, value: number | null, change: (value: number | null) => void, min = 0, max?: number) => <label className="sf-field">{label}<input type="number" min={min} max={max} step="0.01" value={value === null || !Number.isFinite(value) ? '' : value} onChange={event => change(event.target.value === '' ? null : Number(event.target.value))} /></label>;
  const sharedInput = (key: 'minimum' | 'reserveMonths' | 'extraIncome' | 'extraExpense' | 'cash' | 'bankRate' | 'months', label: string) => input(label, state[key], value => shared(key, value ?? NaN), key === 'bankRate' ? -99.99 : key === 'months' ? 1 : 0, key === 'bankRate' ? 100 : key === 'months' ? 600 : undefined);
  const metric = (label: string, value: string, note?: string) => <div className="sf-metric"><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>;
  const result = (c: ReturnType<typeof calculate>) => <div className="sf-result">{!c.valid ? <div className="sf-alert" role="alert">{c.errors.map(error => <p key={error}>{error === 'unknown' ? m.unknown : error === 'invalid' ? m.invalid : error === 'rate' ? m.rateError : error === 'horizon' ? m.horizonError : `${m.over} ${money(c.over)} / ${m.month.toLowerCase()}`}</p>)}<p>{m.noProjection}</p></div> : <><div className="sf-result-grid">{metric(m.margin, money(c.margin))}{metric(m.free, money(Math.max(0, c.margin! - c.assigned)))}{metric(m.liquid, c.complete ? money(c.ending?.liquid) : `${m.stopped} ${c.stopped}`)}{metric(m.total, c.complete ? money(c.ending?.total) : '—')}{metric(m.capacity, money(c.trip?.capacity))}</div>{c.margin! < 0 && <p className="sf-alert">{m.deficit}</p>}{c.holds > 0 && <p className="sf-alert">{m.reserveHeld}</p>}<p>{c.trip?.funded ? m.tripFunded : m.tripPending} {c.target > state.months && m.outside}</p></>}</div>;
  const basicFields = (key: 'A' | 'B', fields: ('income' | 'essential' | 'discretionary' | 'tripCost')[]) => fields.map(field => <div key={field}>{input(m[field], state[key][field], value => update(key, field, value))}<small>{field === 'income' || field === 'essential' ? m.projected : key === 'B' ? `${money(state.B[field] - state.A[field])} ${m.difference}` : m.projected}</small></div>);
  const allocations = (key: 'A' | 'B') => state.buckets.map(bucket => <div key={bucket.id}>{input(`${bucketName(bucket.id)} · ${m.contribution}`, state[key].contributions[bucket.id], value => setState(old => ({ ...old, [key]: { ...old[key], contributions: { ...old[key].contributions, [bucket.id]: value ?? NaN } } })))}<small>{key === 'B' ? `${money(state.B.contributions[bucket.id] - state.A.contributions[bucket.id])} ${m.difference}` : m.projected}</small></div>);
  const card = (key: 'A' | 'B') => <article className={`sf-future sf-future-${key}`}><header><span>{key}</span><div><small>{key === 'A' ? m.current : m.alternative}</small><h3>{key === 'A' ? m.currentTitle : m.alternativeTitle}</h3></div></header><div className="sf-edit-grid">{basicFields(key, ['income', 'essential', 'discretionary'])}{allocations(key)}{basicFields(key, ['tripCost'])}</div>{result(key === 'A' ? a : b)}</article>;
  const table = (c: ReturnType<typeof calculate>, key: string) => <details className="sf-data"><summary>{m.data} · {key}<span className="sf-chevron" aria-hidden="true" /></summary><div className="sf-table-wrap"><table><thead><tr>{[m.month, m.cash, ...state.buckets.map(bucket => bucketName(bucket.id)), ...state.buckets.map(bucket => `${bucketName(bucket.id)} · ${m.contribution}`), m.growth, m.paidTrip, m.total].map((label, i) => <th key={i}>{label}</th>)}</tr></thead><tbody>{c.visible.map(row => <tr key={row.month}>{[String(row.month), money(row.cash), ...state.buckets.map(bucket => money(row.balances[bucket.id])), ...state.buckets.map(bucket => money(row.contributions[bucket.id])), money(row.growth), money(row.trip), money(row.total)].map((value, i) => <td key={i}>{value}</td>)}</tr>)}</tbody></table></div></details>;
  const graphMax = Math.max(a.floor, ...a.visible.map(row => row.liquid), ...b.visible.map(row => row.liquid), 1) * 1.1;
  const points = (c: ReturnType<typeof calculate>) => c.visible.map(row => `${30 + row.month / state.months * 700},${180 - row.liquid / graphMax * 150}`).join(' ');
  const refresh = () => { edited.current = { A: { income: false, essential: false }, B: { income: false, essential: false } }; setState(old => ({ ...old, A: { ...old.A, income, essential: expense }, B: { ...old.B, income, essential: expense } })); };
  const save = () => { try { if (!storageKey) throw new Error("Session unavailable"); localStorage.setItem(storageKey, JSON.stringify({ version: 1, state, name })); setStatus(m.saved); } catch { setStatus(m.saveFailed); } };
  const load = () => { try { if (!storageKey) throw new Error("Session unavailable"); const raw = localStorage.getItem(storageKey); if (!raw) { setStatus(m.none); return; } const saved = JSON.parse(raw); if (saved.version !== 1 || typeof saved.name !== 'string' || !validStoredState(saved.state)) throw new Error('Invalid comparison'); edited.current = { A: { income: true, essential: true }, B: { income: true, essential: true } }; setState(saved.state); setName(saved.name); setStatus(m.loaded); } catch { setStatus(m.saveFailed); } };
  return <section className="sf-selected" aria-busy={loading}><header className="sf-heading"><div><p className="sf-kicker">{m.kicker}</p><h1>{m.title}</h1><h2>{m.subtitle}</h2></div><p>{m.simulation}</p></header><div className="sf-horizons">{[1,4,7,10].map(years => <button type="button" key={years} aria-pressed={state.months === years * 12} onClick={() => shared('months', years * 12)}>{years} {years === 1 ? m.year : m.years}</button>)}<button type="button" onClick={() => { edited.current = { A: { income: false, essential: false }, B: { income: false, essential: false } }; const reset = defaults(); reset.A.income = reset.B.income = income; reset.A.essential = reset.B.essential = expense; setState(reset); setTab(0); setStep(0); setName(''); setStatus(''); }}>{m.reset}</button></div>
    <details className="sf-editor"><summary><b>{m.shared}</b><span>{m.household} · {m.balances} · {m.rates}</span><span className="sf-chevron" aria-hidden="true" /></summary><div className="sf-editor-body"><fieldset><legend>{m.household} · NZD</legend>{sharedInput('extraIncome',m.extraIncome)}{sharedInput('extraExpense',m.extraExpense)}{sharedInput('minimum',m.minimum)}{sharedInput('reserveMonths',m.reserveMonths)}{sharedInput('months',m.months)}<label className="sf-field">{m.start}<input type="month" value={state.start} onChange={event => shared('start',event.target.value)} /></label><label className="sf-field">{m.tripDate}<input type="month" value={state.tripDate} onChange={event => shared('tripDate',event.target.value)} /></label>{sharedInput('cash',m.cash)}{sharedInput('bankRate',m.bankRate)}<label className="sf-check"><input type="checkbox" checked={state.protectReserve} onChange={event => shared('protectReserve',event.target.checked)} />{m.protect}</label></fieldset><fieldset><legend>{m.balances} · {m.rates}</legend>{state.buckets.map(bucket => <div className="sf-bucket" key={bucket.id}><label className="sf-field">{m.bucketName}<input value={bucket.name || (bucket.id === 'emergency' ? m.emergency : '')} onChange={event => setState(old => ({ ...old,buckets:old.buckets.map(item => item.id === bucket.id ? {...item,name:event.target.value} : item) }))} /></label><label className="sf-field">{m.kind}<select disabled={['emergency','shares','bitcoin'].includes(bucket.id)} value={bucket.kind} onChange={event => setState(old => ({...old,buckets:old.buckets.map(item => item.id === bucket.id ? {...item,kind:event.target.value as typeof bucket.kind} : item)}))}><option value="cash">{m.cashKind}</option><option value="portfolio">{m.portfolioKind}</option><option value="bitcoin">{m.bitcoinKind}</option></select></label>{input(m.initial,bucket.initial,value => setState(old => ({...old,buckets:old.buckets.map(item => item.id === bucket.id ? {...item,initial:value ?? NaN} : item)})))}{input(m.rate,bucket.rate,value => setState(old => ({...old,buckets:old.buckets.map(item => item.id === bucket.id ? {...item,rate:value ?? NaN} : item)})),-99.99,100)}{!['emergency','shares','bitcoin'].includes(bucket.id) && <button type="button" onClick={() => setState(old => ({...old,buckets:old.buckets.filter(item => item.id !== bucket.id)}))}>{m.remove}</button>}</div>)}<button type="button" onClick={() => setState(old => { const id = crypto.randomUUID(); return {...old,buckets:[...old.buckets,{id,name:'',kind:'cash',initial:0,rate:0}],A:{...old.A,contributions:{...old.A.contributions,[id]:0}},B:{...old.B,contributions:{...old.B.contributions,[id]:0}}}; })}>{m.add}</button></fieldset></div><p>{m.assumptions}</p></details>
    <details className="sf-coverage"><summary>{m.coverage}<span className="sf-chevron" aria-hidden="true" /></summary>{coverage}<p>{m.notKnown}</p><div className="sf-result-grid">{metric(m.income,money(income),m.observed)}{metric(m.essential,money(expense),m.observed)}</div><button type="button" onClick={refresh} disabled={loading || income === null && expense === null}>{m.refresh}</button></details>
    <p className="sf-risk">{m.assumptions}</p>
    <div className="sf-planstrip">{metric(m.income,money(a.income),m.projected)}{metric(m.essential,money(a.expense),m.projected)}{metric(m.margin,money(a.margin))}{metric(m.assigned,money(a.assigned))}</div>
    <nav className="sf-tabs" role="tablist" aria-label={m.kicker}>{[m.compare,m.compass,m.decision].map((label,index) => <button type="button" id={`forecast-tab-${index}`} key={label} role="tab" aria-selected={tab === index} aria-controls={`forecast-panel-${index}`} tabIndex={tab === index ? 0 : -1} onClick={() => setTab(index)} onKeyDown={event => { if (!['ArrowLeft','ArrowRight','Home','End'].includes(event.key)) return; event.preventDefault(); const next = event.key === 'Home' ? 0 : event.key === 'End' ? 2 : (index + (event.key === 'ArrowRight' ? 1 : 2)) % 3; setTab(next); document.getElementById(`forecast-tab-${next}`)?.focus(); }}><small>0{index+1}</small>{label}</button>)}</nav>
    <section id={`forecast-panel-${tab}`} role="tabpanel" aria-labelledby={`forecast-tab-${tab}`}>
      {tab === 0 ? <><p className="sf-shared-note">{m.sharedNote}</p><div className="sf-pair">{card('A')}{card('B')}</div><div className="sf-actions"><button type="button" onClick={() => { edited.current.B = {income:true,essential:true};setState(old => ({...old,B:structuredClone(old.A)})); }}>{m.copy}</button><button type="button" disabled={!b.valid} onClick={() => { edited.current.A = {income:true,essential:true};setState(old => ({...old,A:structuredClone(old.B)})); }}>{m.apply}</button><small>{m.simulation}</small></div><section className="sf-differences"><h3>{m.changes}</h3>{metric(m.margin,money(a.margin === null || b.margin === null ? null : b.margin-a.margin))}{metric(m.liquid,a.complete && b.complete ? money(b.ending!.liquid-a.ending!.liquid) : m.comparable)}{metric(m.assigned,money(b.assigned-a.assigned))}</section><section className="sf-panel"><h3>{a.valid && b.valid ? m.chart : m.chartPending}</h3>{a.valid && b.valid && <><p>{m.chartHint}</p><svg viewBox="0 0 760 220" role="img" aria-label={m.chart}><line x1="30" x2="730" y1={180-a.floor/graphMax*150} y2={180-a.floor/graphMax*150} className="sf-reserve-line" /><polyline points={points(a)} className="sf-line-a" /><polyline points={points(b)} className="sf-line-b" /><text x="30" y="210">0</text><text x="685" y="210">{state.months}</text><text x="30" y="20">{money(graphMax)}</text></svg>{table(a,'A')}{table(b,'B')}</>}</section></> : tab === 1 ? <><section className="sf-compass"><div><p className="sf-kicker">{m.compass}</p><h2>{m.living}</h2><p>{m.compassNote}</p></div><div>{metric(m.margin,`A ${money(a.margin)} · B ${money(b.margin)}`)}{metric(m.assigned,`A ${money(a.assigned)} · B ${money(b.assigned)}`)}{metric(m.reserve,money(a.floor))}</div></section><div className="sf-pair"><article className="sf-panel"><h3>A</h3>{result(a)}</article><article className="sf-panel"><h3>B</h3>{result(b)}</article></div></> : <section className="sf-guide"><nav>{m.steps.map((label,index) => <button type="button" key={label} aria-pressed={step === index} onClick={() => setStep(index)}>{label}</button>)}</nav><h3>{m.questions[step]}</h3><p>{m.same}</p><div className="sf-pair">{(['A','B'] as const).map(key => <section key={key}><h4>{key}</h4><div className="sf-edit-grid">{step === 0 ? basicFields(key,['income','essential','discretionary']) : step === 1 ? allocations(key) : basicFields(key,['tripCost'])}</div>{step === 2 && result(key === 'A' ? a : b)}</section>)}</div><div className="sf-actions"><button type="button" onClick={() => setTab(0)}>{m.back}</button>{step < 2 && <button type="button" onClick={() => setStep(step+1)}>{m.next}</button>}</div></section>}
    </section><section className="sf-save"><label className="sf-field">{m.name}<input value={name} onChange={event => setName(event.target.value)} /></label><button type="button" onClick={save} disabled={!storageKey}>{m.save}</button><button type="button" onClick={load} disabled={!storageKey}>{m.load}</button><p>{m.local}</p></section><details className="sf-method"><summary>{m.methodology}<span className="sf-chevron" aria-hidden="true" /></summary><p>{m.method}</p><p>{m.assumptions}</p></details><p role="status">{status}</p>
  </section>;
}
function validStoredState(value: unknown): value is ForecastState {
  if (!value || typeof value !== 'object') return false;
  const state = value as ForecastState;
  if (!Array.isArray(state.buckets) || state.buckets.length < 1 || state.buckets.length > 50 || !state.buckets.every(bucket => typeof bucket.id === 'string' && typeof bucket.name === 'string' && ['cash','portfolio','bitcoin'].includes(bucket.kind)) || typeof state.start !== 'string' || typeof state.tripDate !== 'string' || typeof state.protectReserve !== 'boolean') return false;
  try { return !calculate(state,'A').errors.some(error => error !== 'over' && error !== 'unknown') && !calculate(state,'B').errors.some(error => error !== 'over' && error !== 'unknown'); } catch { return false; }
}
